- platform: scrape
  resource: https://elen.nu/dagens-spotpris/se3-stockholm/
  name: Electricity price SE3
  select: ".text-lg.font-bold"
  device_class: "monetary"
  index: 1
  value_template: '{{ value | replace (",", ".") | float | multiply(0.01) }}'
  unit_of_measurement: "SEK/kWh"
