sensor:
  - platform: scrape
    resource: https://elen.nu/timpriser-pa-el-for-elomrade-se3-stockholm/
    name: Electricity price
    select: ".text-lg:is(span)"
    index: 1
    value_template: '{{ value | replace (",", ".") | float }}'
    unit_of_measurement: "öre/kWh"
